name: CI/CD React App with Docker

on:
  push:
    branches: [ "main" ] # Atau branch utama kamu, misal "master"
  pull_request:
    branches: [ "main" ] # Opsional: jalankan juga pada pull request ke main

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Diperlukan untuk push ke GitHub Container Registry

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}
          # Contoh tags:
          # - type=sha,prefix= # Tag dengan commit SHA pendek
          # - type=ref,event=branch # Tag dengan nama branch
          # - type=raw,value=latest,enable={{is_default_branch}} # Tag 'latest' jika di branch utama

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }} # Hanya push jika bukan pull request
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
